version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      - PORT=3001
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=gamedb
      - DB_USER=postgres
      - DB_PASSWORD=d2h5bm90Z29nZXRhbGlmZS15b3UtZm9vb29vb2w=
    networks:
      - app-network

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=d2h5bm90Z29nZXRhbGlmZS15b3UtZm9vb29vb2w=
      - POSTGRES_DB=gamedb
    volumes:
      - ./backend/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: