apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: memory-game
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: acrname.azurecr.io/memory-game-frontend:latest    # memory-game-frontend:latest (keep for local deplyment with minikube)
          pullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          env:
            - name: REACT_APP_API_URL
              value: "/api"  # This will be handled by the ingress
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: memory-game
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP    #for minikube deployment (remove tcp)
  selector:
    app: frontend
  type: LoadBalancer  #for minikube deployment (change this to cluster IP)