apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: memory-game-ingress
  namespace: memory-game
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    prometheus.io/scrape: "true"
    prometheus.io/port: "10254"
spec:
  rules:
    - host: memory-game.local  # For local development with Minikube
      http:
        paths:
          - path: /api/(.*)
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80