apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: memory-game
type: Opaque
data:
  # These are base64 encoded values
  # In a real production environment, use a proper secret management solution
  POSTGRES_USER: cG9zdGdyZXM=  # postgres
  POSTGRES_PASSWORD: d2h5bm90Z29nZXRhbGlmZS15b3UtZm9vb29vb2w=  # Password123
  POSTGRES_DB: Z2FtZWRi  # gamedb
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: memory-game
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=  # postgres
  DB_PASSWORD: d2h5bm90Z29nZXRhbGlmZS15b3UtZm9vb29vb2w=  # Password123
  DB_NAME: Z2FtZWRi  # gamedb