# kubernetes/application/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: memory-game
type: Opaque
data:
  # Get these values from Terraform outputs after provisioning
  DB_HOST: <base64-encoded-azure-pg-fqdn>        # your-server.postgres.database.azure.com
  DB_USER: <base64-encoded-azure-pg-username>    # From terraform output
  DB_PASSWORD: <base64-encoded-azure-pg-password> # From terraform output  
  DB_NAME: Z2FtZWRi                              # gamedb (base64)
  DB_PORT: NTQzMg==                              # 5432 (base64)


# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: postgres-secrets
#   namespace: memory-game
# type: Opaque
# data:
#   POSTGRES_USER: cG9zdGdyZXM=            
#   POSTGRES_PASSWORD: cGFzc3dvcmQ=          
#   POSTGRES_DB: Z2FtZWRi                   
# ---

# apiVersion: v1
# kind: Secret
# metadata:
#   name: backend-secrets
#   namespace: memory-game
# type: Opaque
# data:
#   DB_USER: cG9zdGdyZXM=                   
#   DB_PASSWORD: cGFzc3dvcmQ=                
#   DB_NAME: Z2FtZWRi                        
