
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: memory-game
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=            
  POSTGRES_PASSWORD: cGFzc3dvcmQ=          
  POSTGRES_DB: Z2FtZWRi                   
---

apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: memory-game
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=                   
  DB_PASSWORD: cGFzc3dvcmQ=                
  DB_NAME: Z2FtZWRi                        
