name: Build and Deploy Backend + Frontend App to AKS

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: false
        type: string

env:
  ACR_LOGIN_SERVER: appacr94.azurecr.io
  ACR_NAME: appacr94
  IMAGE_TAG: ${{ github.sha }}
  BACKEND_IMAGE_NAME: memory-game-backend
  FRONTEND_IMAGE_NAME: memory-game-frontend
  BACKEND_DEPLOYMENT_NAME: backend
  FRONTEND_DEPLOYMENT_NAME: frontend
  NAMESPACE: memory-game
  KUBECONFIG: ~/.kube/config

  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  JUMPBOX_PASSWORD: ${{ secrets.JUMPBOX_PASSWORD }}
  GRAFANA_PASSWORD: ${{ secrets.GRAFANA_PASSWORD }}

jobs:
  build-push-deploy:
    name: Build, Push to ACR, Deploy to AKS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Login to Azure Container Registry (ACR)
      run: |
        az acr login --name $ACR_NAME

    - name: Build and Push Backend and Frontend Images
      run: |
        echo "⚡ Building and Pushing Backend Image..."
        docker build -t $ACR_LOGIN_SERVER/$BACKEND_IMAGE_NAME:$IMAGE_TAG ./application/backend
        docker push $ACR_LOGIN_SERVER/$BACKEND_IMAGE_NAME:$IMAGE_TAG

        echo "⚡ Building and Pushing Frontend Image..."
        docker build -t $ACR_LOGIN_SERVER/$FRONTEND_IMAGE_NAME:$IMAGE_TAG ./application/frontend
        docker push $ACR_LOGIN_SERVER/$FRONTEND_IMAGE_NAME:$IMAGE_TAG

    - name: Install sshpass
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

    - name: Copy Kubernetes Manifests to Bastion
      env:
        BASTION_HOST: ${{ secrets.JUMPBOX_IP }}
        BASTION_USER: azureuser
        BASTION_PASSWORD: ${{ secrets.JUMPBOX_PASSWORD }}
      run: |
        echo "⚡ Copying manifests to Bastion Host..."
        sshpass -p "$BASTION_PASSWORD" scp -o StrictHostKeyChecking=no -r ./kubernetes/application $BASTION_USER@$BASTION_HOST:/tmp/application

    - name: Deploy Backend and Frontend from Bastion
      env:
        BASTION_HOST: ${{ secrets.JUMPBOX_IP }}
        BASTION_USER: azureuser
        BASTION_PASSWORD: ${{ secrets.JUMPBOX_PASSWORD }}
      run: |
        echo "⚡ Connecting to Bastion and deploying..."
        sshpass -p "$BASTION_PASSWORD" ssh -o StrictHostKeyChecking=no "$BASTION_USER@$BASTION_HOST" bash << EOF
          set -e
          echo "⚡ Applying Namespace and Secrets..."
          kubectl apply -f /tmp/application/namespace.yaml
          kubectl apply -f /tmp/application/secrets.yaml

          echo "⚡ Updating Backend Deployment..."
          kubectl set image deployment/$BACKEND_DEPLOYMENT_NAME backend=$ACR_LOGIN_SERVER/$BACKEND_IMAGE_NAME:$IMAGE_TAG -n $NAMESPACE

          echo "⚡ Updating Frontend Deployment..."
          kubectl set image deployment/$FRONTEND_DEPLOYMENT_NAME frontend=$ACR_LOGIN_SERVER/$FRONTEND_IMAGE_NAME:$IMAGE_TAG -n $NAMESPACE

          echo "⚡ Applying Ingress..."
          kubectl apply -f /tmp/application/ingress.yaml

          echo "✅ Deployment successful!"
        EOF
